sudo: required
language: cpp
dist: bionic
matrix:
  include:
  - compiler: gcc
    env:
    - CXX_COMPILER=g++-7
    - CC_COMPILER=gcc-7
    - FC_COMPILER=gfortran-7
    - OMPI_CC=gcc-7
    - OMPI_FC=gfortran-7
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7
        - g++-7
        - gfortran-7
before_install:
- sudo apt-get update
- sudo apt-get install python3
before_script:
- export FC=$FC_COMPILER
- export CC=$CC_COMPILER
- export CXX=$CXX_COMPILER
script:
- echo "Testing out-of-source cmake build"
- export OMNI_SRC=$(pwd)
- export OMNI_BUILD=${HOME}/omni-build
- export OMNI_INSTALL=${HOME}/omni-install
- mkdir ${OMNI_BUILD}
- mkdir ${OMNI_INSTALL}
- cd ${OMNI_BUILD}
- cmake -S ${OMNI_SRC} -DCMAKE_INSTALL_PREFIX=${OMNI_INSTALL} -DPython3_EXECUTABLE=$(which python3)
- make -j
- make install
- make -j test-ffront-c
- make -j test-ffront-cpp
- echo "Testing in-source GNU Make build"
- cd ${OMNI_SRC}
- ./configure && make && make test
